### ISSUE TITLE
zarafa zcp 7.2.x

### ISSUE THREAD

**Issue by marco-uniware** [zarafagroupware/zarafa-tools#20]
cleanup scripts is not working in zcp 7.2.x
any ideas or updates?

**Comment by mstiem** [comment]
same here - vote  +1

**Comment by marco-uniware** [comment]
they are working on a better and new script (python), i received a version, worked until 7.2.1, they changed it again,
They told me, that they will make a new one very soon, and also wil share it to everybody

**Comment by mstiem** [comment]
Great thanks for that information.   :+1:

**Comment by RobinvG** [comment]
Hi mstiem,

The new version is uploaded

**Comment by mstiem** [comment]
Awesome!   Thanks guys! :thumbsup::thumbsup:

**Comment by marco-uniware** [comment]
@RobinvG is that the newest version?, i had a error when date field was absent, somebody at zarafa changed a file last friday 19-2

**Comment by RobinvG** [comment]
@marco-uniware . Yes the date is changed to 'PR_LAST_MODIFICATION_TIME' instead of the received date.

**Comment by marco-uniware** [comment]
ok thanx

**Comment by fbartels** [comment]
issue seems to be resolved then
