### ISSUE TITLE
Wrong Birthday prior 1956

### ISSUE THREAD

**Issue by snoopyf** [zarafagroupware/zarafa-tools#22]
Hi everybody,

came across this issue:

A contacts birthday is set prior 1956-10-01 (1956-04-12) per Zarafas WebApp. In the WebApp and synced via Z-Push to different devices, the birthday everywhere is correctly displayed as 1956-04-12.

When downloading the .vcf with carddav.php, the resulting BDAY in the .vcf is 1956-04-11.
I tracked down that this must have sth. to do with summertime calcs (as in Wikipedia can be read, it is effective since 1956 till now). 

With Firebug I debugged that the BDay value sent from Zarafas WebApp to the Zarafa Server is in Unix Time ("1956-04-12 00:00:00" => -433044000).

I inserted some debugging to carddav.php around this line:

`
if (isset($contactprops[PR_BIRTHDAY]))                                          $vcard->setBirthday                     ($this->toUTF8(date('Y-m-d', $contactprops[PR_BIRTHDAY])));
`

These returned:
`
TZ: Europe/Berlin
This is PR_BIRTHDAY:-433044000
and after convert: 1956-04-11 23:00:00
`

As one can see, the returning date is one hour behind, so the day results to 1956-04-11.

For testing I changed the contacts birthday to 1956-10-01 in Zarafas WebApp, which sent the Unix Time -418179600 to the Server.
Then the .vcf generated by carddav.php is correct and my inserted debug lines give:

`
TZ: Europe/Berlin
This is PR_BIRTHDAY:-418179600
and after convert: 1956-10-01 00:00:00
`

As one can see, the hour (and so the day, too) is correct this time...

Now don't really know what has to be changed in carddav.php for making it converting the dates prior 1956-10-01 correctly (as the Zarafas WebApp and Z-Push obviously do).

Any hint?

Thx in advance!

**Comment by RobinvG** [comment]
Hi Snoopyf, 

Sabredav-zarafa is not from zarafa but from 1A 
https://github.com/1afa/sabre-zarafa

Best regards,

Robin

**Comment by snoopyf** [comment]
Hi Robin,

where did I say I'm using sabre-sarafa? As I wrote, I'm using your "carddav.php" from this project here:

https://github.com/zarafagroupware/zarafa-tools/tree/master/contacts/carddav

Regards
Snoopy

**Comment by RobinvG** [comment]
Ah , i didn't even know we had that on our github, but the the answer stays the same, this script is not ours but from  'Rainer Voigt, Amin Baumeler'  and it is not changed in 3 years time. 

But, please take a look at sabredav-zarafa  that project is still being maintained

**Comment by snoopyf** [comment]
OK, didn't really realize that it seems to be dead.. 
I tried sabredav-zarafa after carddav.php from here... With sabre-zarafa there is the same problem so it seems to be a more general (PHP?) one... Perhaps you have an idea or a hint where to look at?

**Comment by RobinvG** [comment]
Please keep in mind that MAPI is using a different timestamp that is normally used. See the documentation below:
https://documentation.zarafa.com/zcp_python_language_binding/conventions.html#mapi-time

**Comment by snoopyf** [comment]
Don't really get the connection between the Date/Time conversions used in Zarafas MAPI Python - Bindings to sabre-dav which completely is written in PHP....
Don't I get it right, that your link concerns just programming Zarafas Mapi in Python?

**Comment by srepmub** [comment]
looking at the MAPI properties for a contact added with webapp, I don't see a timezone anywhere.. plus webapp doesn't use the correct timezone always when calculating time stamps.. so what should other clients do when encountering this? a solution we use elsewhere where there are no/wrong timezones used by webapp, and we are only interested in the _date_ part anyway (hint: allday events), is to just round to the closest date. so 23:00 becomes 24:00, so the next day.. it ain't pretty but without timezones it's not going to be pretty.

**Comment by snoopyf** [comment]
In Zarafas WebApps config.php a timezone property can be set if there is no default one in php.ini.
I found out, that this behaviour must have something to do with different calculations between JavaScript and PHP. 
On a system completely configured with "Europe/Berlin" as timezone the timestamp -433044000
results in "1956-03-11 23:00:00" in PHP and in bash also. In germany summertime exists since 1980 and both PHP and bash respect that.
When checking the timestamp with JavaScript in this way:

`<script language="JavaScript">
        var d=new Date(-433044000*1000); // *1000 because JavaScript works with milliseconds
        document.write(d);
</script>
`
This is the result:

`Thu Apr 12 1956 00:00:00 GMT+0200 (CET) `

So 1 hour difference to PHP/bash, no matter which browser or OS (tested with current Chrome/Firefox on Linux or IE11 on Windows).

So I currently assume, it is the JavaScript part of Zarafas WebApp, which does some wrong date calculation from the entered "human readable" date to unixtime when saving a contact.
